importScripts("local-auth-headers.js", "send-url.js");

// In-memory only — never persist the loopback token (YTT-435 / YTT-442).
let _localTokenMemory = null;
const NATIVE_HOST_NAME = "com.transcribed.host";
const CAPTION_EXTRACT_TIMEOUT_MS = 2500;

function callNativeHostCmd(cmd, payload = {}, timeoutMs = 5000) {
  return new Promise((resolve, reject) => {
    let port;
    try {
      port = chrome.runtime.connectNative(NATIVE_HOST_NAME);
    } catch {
      reject(new Error("native_host_unavailable"));
      return;
    }
    const timer = setTimeout(() => {
      try {
        port.disconnect();
      } catch {
        /* ignore */
      }
      reject(new Error("native_host_timeout"));
    }, timeoutMs);
    port.onMessage.addListener((msg) => {
      clearTimeout(timer);
      try {
        port.disconnect();
      } catch {
        /* ignore */
      }
      resolve(msg);
    });
    port.onDisconnect.addListener(() => {
      clearTimeout(timer);
      const err = chrome.runtime.lastError?.message || "disconnected";
      reject(new Error(err));
    });
    const id = Math.random().toString(36).slice(2);
    port.postMessage({ id, cmd, ...payload });
  });
}

function youtubeVideoId(url) {
  try {
    const u = new URL(url);
    const host = u.hostname.replace(/^www\./, "");
    if (host !== "youtube.com" && host !== "m.youtube.com") return null;
    if (u.pathname === "/watch") return u.searchParams.get("v");
    if (u.pathname.startsWith("/shorts/"))
      return u.pathname.split("/shorts/")[1]?.split("/")[0];
    if (u.pathname.startsWith("/embed/"))
      return u.pathname.split("/embed/")[1]?.split("/")[0];
  } catch { /* ignore */ }
  return null;
}

async function findYouTubeTabForUrl(targetUrl) {
  const targetVid = youtubeVideoId(targetUrl);
  if (!targetVid) return null;
  try {
    const tabs = await chrome.tabs.query({ url: ["*://*.youtube.com/*", "*://m.youtube.com/*"] });
    const exact = tabs.find((t) => t.url === targetUrl);
    if (exact) return exact;
    return tabs.find((t) => youtubeVideoId(t.url || "") === targetVid) || null;
  } catch {
    return null;
  }
}

function sendMessageWithTimeout(tabId, message, timeoutMs) {
  return new Promise((resolve) => {
    let settled = false;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      resolve(null);
    }, timeoutMs);
    try {
      chrome.tabs.sendMessage(tabId, message, (response) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        if (chrome.runtime.lastError) {
          resolve(null);
          return;
        }
        resolve(response ?? null);
      });
    } catch {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(null);
    }
  });
}

async function tryExtractCaptions(url, title) {
  const tab = await findYouTubeTabForUrl(url);
  if (!tab?.id) {
    console.log("[ytt-bg] caption fast-path: no matching youtube tab", { url });
    return null;
  }
  let response = await sendMessageWithTimeout(
    tab.id,
    { type: "EXTRACT_CAPTIONS" },
    CAPTION_EXTRACT_TIMEOUT_MS
  );
  if (response === null) {
    console.log("[ytt-bg] caption fast-path: no listener — injecting + retrying", { tabId: tab.id });
    try {
      await chrome.scripting.executeScript({
        target: { tabId: tab.id },
        files: ["content.js"],
        injectImmediately: true,
      });
      await new Promise((r) => setTimeout(r, 100));
      response = await sendMessageWithTimeout(
        tab.id,
        { type: "EXTRACT_CAPTIONS" },
        CAPTION_EXTRACT_TIMEOUT_MS
      );
    } catch (err) {
      console.log("[ytt-bg] caption fast-path: inject failed", err?.message || err);
      return null;
    }
  }
  console.log("[ytt-bg] caption fast-path response", {
    tabId: tab.id,
    ok: !!response?.ok,
    segments: Array.isArray(response?.segments) ? response.segments.length : 0,
    error: response?.error || null,
  });
  if (!response?.ok || !Array.isArray(response.segments) || !response.segments.length) {
    return null;
  }
  return {
    segments: response.segments,
    title: title || "",
    languageCode: response.languageCode || "",
    isAutoGenerated: !!response.isAutoGenerated,
  };
}

async function getLocalApiToken() {
  if (_localTokenMemory) return { ok: true, token: _localTokenMemory };
  
  let res;
  try {
    res = await callNativeHostCmd("getLocalToken", {}, 5000);
  } catch (err) {
    // Native host unavailable, timeout, or disconnect
    return { ok: false, reason: "unreachable" };
  }
  
  if (res?.ok && typeof res.token === "string" && res.token.length > 0) {
    _localTokenMemory = res.token;
    return { ok: true, token: _localTokenMemory };
  }
  
  // YTT-448: Native host { ok:false } maps to reason "other" (not unauthorized)
  if (res?.ok === false) {
    return { ok: false, reason: "other" };
  }
  
  // Host OK but token missing/empty
  return { ok: false, reason: "unauthorized" };
}

function clearLocalTokenMemory() {
  _localTokenMemory = null;
}

async function sendPageUrl(pageUrl, title) {
  const tokenResult = await getLocalApiToken();
  
  // Native host unavailable
  if (!tokenResult.ok && tokenResult.reason === "unreachable") {
    return { ok: false, reason: "unreachable" };
  }
  
  // Host OK but no token
  if (!tokenResult.ok && tokenResult.reason === "unauthorized") {
    return { ok: false, reason: "unauthorized" };
  }
  
  // YTT-448: Native host { ok:false } maps to other
  if (!tokenResult.ok && tokenResult.reason === "other") {
    return { ok: false, reason: "other" };
  }
  
  // Try caption extraction for YouTube URLs
  const captions = youtubeVideoId(pageUrl) ? await tryExtractCaptions(pageUrl, title) : null;
  
  // Build request with token and optional segments
  const request = buildLocalSendRequest(pageUrl, tokenResult.token, captions);
  if (!request.ok) {
    // Token present but request build failed (bad URL etc.)
    return { ok: false, reason: "other" };
  }

  let res;
  try {
    res = await fetch(request.url, {
      method: "POST",
      headers: request.headers,
      credentials: "omit",
      body: request.body,
    });
  } catch {
    // Fetch failed after token was present
    return { ok: false, reason: "unreachable" };
  }

  if (res.status === 401) {
    clearLocalTokenMemory();
    return { ok: false, reason: "unauthorized" };
  }
  
  if (!res.ok) {
    // YTT-448: Never return server error text
    return { ok: false, reason: "other" };
  }
  
  let data;
  try {
    data = await res.json();
  } catch {
    return { ok: false, reason: "other" };
  }

  // YTT-448: Validate transcriptId format before success
  if (typeof data?.id !== "string" || !/^[A-Za-z0-9_-]{1,128}$/.test(data.id)) {
    return { ok: false, reason: "other" };
  }

  return { ok: true, transcriptId: data.id };
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message?.type === "CLOSE_PANEL") {
    chrome.sidePanel.setOptions({ enabled: false }).then(() => {
      chrome.sidePanel.setOptions({ enabled: true });
    }).catch(() => {});
    return;
  }
  if (message?.type !== "SEND_PAGE_URL") return;
  if (sender?.id !== chrome.runtime.id) {
    sendResponse({ ok: false });
    return;
  }
  sendPageUrl(message.url, message.title)
    .then((result) => sendResponse(result))
    .catch(() => sendResponse({ ok: false }));
  return true;
});

chrome.sidePanel.setOptions({ path: "popup.html", enabled: true }).catch(() => {});

chrome.sidePanel
  .setPanelBehavior({ openPanelOnActionClick: false })
  .catch(() => {});

chrome.action.onClicked.addListener((tab) => {
  if (!Number.isInteger(tab.windowId)) return;
  chrome.sidePanel.open({ windowId: tab.windowId });
});
