"use strict";

/**
 * LOCAL one-tap send (YTT-442).
 * The extension posts the current page URL to loopback. The Bearer token
 * stays in the Authorization header only — never in the URL, body, or storage.
 */

const LOCAL_SEND_ENDPOINT = "http://127.0.0.1:19720/api/transcripts";
const LOOPBACK_ORIGINS = [
  "http://127.0.0.1:19720",
  "http://127.0.0.1:19721",
];

function isSecretQueryKey(key) {
  const str = String(key || "");
  // Normalize: lowercase and strip hyphens/underscores for matching
  const normalized = str.toLowerCase().replace(/[-_]/g, "");
  
  // Base secret names (normalized)
  const secretBases = [
    "token",
    "accesstoken",
    "refreshtoken",
    "idtoken",
    "apikey",
    "privatetoken",
    "password",
    "auth",
    "authorization",
    "secret",
    "clientsecret",
    "jwt",
    "code", // OAuth authorization code
    "yttx",
  ];
  
  if (secretBases.includes(normalized)) {
    return true;
  }
  
  // Prefix patterns (case-insensitive, stripped)
  if (normalized.startsWith("xapi") || // x-api-key, x-api-token, etc.
      normalized.startsWith("xamz") || // X-Amz-Security-Token, X-Amz-Signature, etc.
      normalized.startsWith("xgoog")) { // x-goog-api-key, etc.
    return true;
  }
  
  return false;
}

function authHeaders(token) {
  if (typeof localAuthHeadersFromToken === "function") {
    return localAuthHeadersFromToken(token);
  }
  return require("./local-auth-headers.js").localAuthHeadersFromToken(token);
}

function stripSecretParams(params, token) {
  for (const key of [...params.keys()]) {
    const value = params.get(key) || "";
    if (isSecretQueryKey(key) || (token && value.includes(token))) {
      params.delete(key);
    }
  }
}

/**
 * http(s) page URL safe to display and POST.
 * Drops userinfo and known secret query/hash params. Returns null otherwise.
 * @param {string} pageUrl
 * @param {string} [token]
 * @returns {string | null}
 */
function normalizePageUrl(pageUrl, token) {
  if (typeof pageUrl !== "string") return null;
  const raw = pageUrl.trim();
  if (!raw || raw.length > 4096) return null;
  if (token && raw.includes(token) && !raw.includes("?") && !raw.includes("#")) {
    return null;
  }

  let parsed;
  try {
    parsed = new URL(raw);
  } catch {
    return null;
  }
  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return null;

  parsed.username = "";
  parsed.password = "";
  stripSecretParams(parsed.searchParams, token);

  if (parsed.hash) {
    const hashBody = parsed.hash.slice(1);
    const hashParams = new URLSearchParams(hashBody);
    const hadPairs = hashBody.includes("=");
    if (hadPairs) {
      stripSecretParams(hashParams, token);
      const next = hashParams.toString();
      parsed.hash = next ? `#${next}` : "";
    } else if (token && parsed.hash.includes(token)) {
      parsed.hash = "";
    }
  }

  const href = parsed.href;
  if (token && href.includes(token)) return null;
  return href;
}

function validateSegments(segments) {
  if (!Array.isArray(segments)) return null;
  if (segments.length === 0) return null;
  if (segments.length > 10000) return null;
  
  const validated = [];
  let totalTextSize = 0;
  const MAX_SEGMENT_TEXT = 2000;
  const MAX_TOTAL_TEXT = 500000;
  
  for (const seg of segments) {
    if (typeof seg !== "object" || seg === null) continue;
    if (typeof seg.start !== "number" || seg.start < 0) continue;
    if (typeof seg.text !== "string") continue;
    const text = seg.text.slice(0, MAX_SEGMENT_TEXT);
    totalTextSize += text.length;
    if (totalTextSize > MAX_TOTAL_TEXT) break;
    
    validated.push({
      start: seg.start,
      duration: typeof seg.duration === "number" && seg.duration >= 0 ? seg.duration : 0,
      text: text,
    });
  }
  
  return validated.length > 0 ? validated : null;
}

/**
 * @param {string} pageUrl
 * @param {string} token
 * @param {object} [captions] - { segments, title, languageCode, isAutoGenerated }
 * @returns {{ ok: true, url: string, headers: Record<string, string>, body: string } | { ok: false }}
 */
function buildLocalSendRequest(pageUrl, token, captions, apiBase) {
  if (!token || typeof token !== "string") return { ok: false };
  const url = normalizePageUrl(pageUrl, token);
  if (!url) return { ok: false };

  const base = typeof apiBase === "string" && apiBase ? apiBase : "http://127.0.0.1:19720";
  let endpoint;
  try {
    endpoint = new URL(`${base.replace(/\/$/, "")}/api/transcripts`);
  } catch {
    return { ok: false };
  }
  if (endpoint.search || endpoint.username || endpoint.password || endpoint.hash) {
    return { ok: false };
  }
  if (!LOOPBACK_ORIGINS.includes(endpoint.origin)) return { ok: false };
  if (endpoint.pathname !== "/api/transcripts") return { ok: false };

  const headers = {
    "Content-Type": "application/json",
    Accept: "application/json",
    ...authHeaders(token),
  };
  const authorization = headers.Authorization;
  if (
    typeof authorization !== "string" ||
    !authorization.startsWith("Bearer ") ||
    authorization.includes(url) ||
    /[\r\n]/.test(authorization)
  ) {
    return { ok: false };
  }

  const payload = { url };
  
  if (captions && typeof captions === "object") {
    const validSegments = validateSegments(captions.segments);
    if (validSegments) {
      payload.segments = validSegments;
      if (typeof captions.title === "string" && captions.title.length > 0) {
        payload.title = captions.title.slice(0, 512);
      }
      if (typeof captions.languageCode === "string") {
        payload.languageCode = captions.languageCode.slice(0, 16);
      }
      if (typeof captions.isAutoGenerated === "boolean") {
        payload.isAutoGenerated = captions.isAutoGenerated;
      }
    }
  }

  const body = JSON.stringify(payload);
  const parsedBody = JSON.parse(body);
  if (!parsedBody.url || parsedBody.url !== url) return { ok: false };
  if (body.includes(token) || endpoint.href.includes(token)) return { ok: false };

  return {
    ok: true,
    url: endpoint.href,
    headers,
    body,
  };
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    LOCAL_SEND_ENDPOINT,
    isSecretQueryKey,
    normalizePageUrl,
    validateSegments,
    buildLocalSendRequest,
  };
}
