const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { buildLocalSendRequest, normalizePageUrl } = require("./send-url.js");

const TOKEN = "a".repeat(64);
const WATCH = "https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=12s";

test("send request posts only the page URL to loopback", () => {
  const request = buildLocalSendRequest(WATCH, TOKEN);
  assert.equal(request.ok, true);
  assert.equal(request.url, "http://127.0.0.1:19720/api/transcripts");
  assert.equal(new URL(request.url).search, "");
  assert.equal(request.headers.Authorization, `Bearer ${TOKEN}`);
  assert.deepEqual(JSON.parse(request.body), { url: WATCH });
  assert.equal(request.body.includes(TOKEN), false);
  assert.equal(request.url.includes(TOKEN), false);
});

test("send request can target the packaged app origin", () => {
  const request = buildLocalSendRequest(WATCH, TOKEN, null, "http://127.0.0.1:19721");
  assert.equal(request.ok, true);
  assert.equal(request.url, "http://127.0.0.1:19721/api/transcripts");
  assert.equal(buildLocalSendRequest(WATCH, TOKEN, null, "http://evil.example").ok, false);
  assert.equal(buildLocalSendRequest(WATCH, TOKEN, null, "http://127.0.0.1:19722").ok, false);
});

test("secret query and hash params are removed before send", () => {
  const dirty =
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ&token=" +
    TOKEN +
    "&api_key=sk-test&yttx=handoff#access_token=hidden";
  const request = buildLocalSendRequest(dirty, TOKEN);
  assert.equal(request.ok, true);
  const sent = new URL(JSON.parse(request.body).url);
  assert.equal(sent.searchParams.get("v"), "dQw4w9WgXcQ");
  assert.equal(sent.searchParams.has("token"), false);
  assert.equal(sent.searchParams.has("api_key"), false);
  assert.equal(sent.searchParams.has("yttx"), false);
  assert.equal(sent.hash.includes("access_token"), false);
  assert.equal(sent.href.includes(TOKEN), false);
  assert.equal(request.body.includes(TOKEN), false);
});

test("userinfo and non-http URLs are not sent", () => {
  const withUser = normalizePageUrl(
    "https://user:secret@www.youtube.com/watch?v=dQw4w9WgXcQ"
  );
  assert.equal(withUser.includes("secret"), false);
  assert.equal(withUser.includes("user"), false);
  assert.equal(normalizePageUrl("chrome-extension://abc/popup.html"), null);
  assert.equal(normalizePageUrl("javascript:alert(1)"), null);
  assert.equal(buildLocalSendRequest(WATCH, "").ok, false);
  assert.equal(buildLocalSendRequest(WATCH, null).ok, false);
});

test("a token embedded outside query params is refused", () => {
  const request = buildLocalSendRequest(
    `https://example.com/${TOKEN}`,
    TOKEN
  );
  assert.equal(request.ok, false);
});

test("buildLocalSendRequest body is always exactly {url:...} even with secret query params", () => {
  const dirtyUrl = "https://example.com/page?api_key=sk-secret&apiKey=test&x-goog-api-key=goog&auth=basic&v=123";
  const request = buildLocalSendRequest(dirtyUrl, TOKEN);
  assert.equal(request.ok, true);
  const parsed = JSON.parse(request.body);
  assert.equal(Object.keys(parsed).length, 1);
  assert.equal(typeof parsed.url, "string");
  assert.equal(parsed.url.includes("api_key"), false);
  assert.equal(parsed.url.includes("apiKey"), false);
  assert.equal(parsed.url.includes("x-goog-api-key"), false);
  assert.equal(parsed.url.includes("auth"), false);
  assert.equal(parsed.url.includes("v=123"), true);
});

test("buildLocalSendRequest includes validated segments when provided", () => {
  const captions = {
    segments: [
      { start: 0, duration: 5, text: "Hello world" },
      { start: 5, duration: 3, text: "Test caption" },
    ],
    title: "Test Video",
    languageCode: "en",
    isAutoGenerated: false,
  };
  const request = buildLocalSendRequest(WATCH, TOKEN, captions);
  assert.equal(request.ok, true);
  const parsed = JSON.parse(request.body);
  assert.equal(parsed.url, WATCH);
  assert.equal(Array.isArray(parsed.segments), true);
  assert.equal(parsed.segments.length, 2);
  assert.equal(parsed.segments[0].text, "Hello world");
  assert.equal(parsed.title, "Test Video");
  assert.equal(parsed.languageCode, "en");
  assert.equal(parsed.isAutoGenerated, false);
  assert.equal(request.body.includes(TOKEN), false);
});

test("buildLocalSendRequest rejects oversized or invalid segments", () => {
  const { validateSegments } = require("./send-url.js");
  assert.equal(validateSegments(null), null);
  assert.equal(validateSegments([]), null);
  assert.equal(validateSegments([{ text: "no start field" }]), null);
  assert.equal(validateSegments([{ start: -5, text: "negative start" }]), null);
  
  const hugeText = "x".repeat(3000);
  const capped = validateSegments([{ start: 0, text: hugeText }]);
  assert.equal(capped[0].text.length, 2000);
  
  const tooMany = Array.from({ length: 15000 }, (_, i) => ({ start: i, text: "x" }));
  assert.equal(validateSegments(tooMany), null);
});

test("secret denylist normalizes keys (lowercase, strip hyphens/underscores)", () => {
  const { isSecretQueryKey } = require("./send-url.js");
  
  // Base names with various casings and separators
  assert.equal(isSecretQueryKey("api_key"), true);
  assert.equal(isSecretQueryKey("API_KEY"), true);
  assert.equal(isSecretQueryKey("api-key"), true);
  assert.equal(isSecretQueryKey("API-KEY"), true);
  assert.equal(isSecretQueryKey("apikey"), true);
  assert.equal(isSecretQueryKey("ApiKey"), true);
  
  assert.equal(isSecretQueryKey("access_token"), true);
  assert.equal(isSecretQueryKey("access-token"), true);
  assert.equal(isSecretQueryKey("ACCESS_TOKEN"), true);
  assert.equal(isSecretQueryKey("accesstoken"), true);
  
  assert.equal(isSecretQueryKey("private_token"), true);
  assert.equal(isSecretQueryKey("private-token"), true);
  assert.equal(isSecretQueryKey("PRIVATE_TOKEN"), true);
  assert.equal(isSecretQueryKey("privatetoken"), true);
  
  assert.equal(isSecretQueryKey("jwt"), true);
  assert.equal(isSecretQueryKey("JWT"), true);
  
  assert.equal(isSecretQueryKey("code"), true); // OAuth code
  assert.equal(isSecretQueryKey("CODE"), true);
});

test("secret denylist matches x-api-*, X-Amz-*, x-goog-* patterns", () => {
  const { isSecretQueryKey } = require("./send-url.js");
  
  // x-api-* patterns
  assert.equal(isSecretQueryKey("x-api-key"), true);
  assert.equal(isSecretQueryKey("X-API-KEY"), true);
  assert.equal(isSecretQueryKey("x_api_key"), true);
  assert.equal(isSecretQueryKey("xapi-token"), true);
  assert.equal(isSecretQueryKey("X_API_TOKEN"), true);
  
  // X-Amz-* patterns (AWS)
  assert.equal(isSecretQueryKey("X-Amz-Security-Token"), true);
  assert.equal(isSecretQueryKey("X-Amz-Signature"), true);
  assert.equal(isSecretQueryKey("x-amz-credential"), true);
  assert.equal(isSecretQueryKey("x_amz_signature"), true);
  
  // x-goog-* patterns (Google)
  assert.equal(isSecretQueryKey("x-goog-api-key"), true);
  assert.equal(isSecretQueryKey("X-GOOG-API-KEY"), true);
  assert.equal(isSecretQueryKey("x_goog_api_key"), true);
  
  // Non-secret keys should not match
  assert.equal(isSecretQueryKey("v"), false);
  assert.equal(isSecretQueryKey("id"), false);
  assert.equal(isSecretQueryKey("timestamp"), false);
  assert.equal(isSecretQueryKey("user"), false);
});

test("send-url has no tokenless helper", () => {
  const send = require("./send-url.js");
  assert.equal(send.buildTokenlessDevSendRequest, undefined);
  const src = fs.readFileSync(path.join(__dirname, "send-url.js"), "utf8");
  assert.doesNotMatch(src, /buildTokenlessDevSendRequest/);
});
